Repository becurrie/titandash, pull requests merged in 2020-04, with the labels that each got.

#479 #480 Fix No Artifact Upgrade Selected On Prestige
  titanbot/titandash/bot/core/bot.py
Labels: bug

#488 #480 Fix No Artifact Upgrade Selected On Prestige
  titanbot/titandash/bot/core/bot.py
Labels: bug

#489 #487 Address 3.9.0 Issues
  titanbot/titandash/bot/core/bot.py
  titanbot/titandash/bot/core/grabber.py
  titanbot/titandash/bot/core/maps.py
  titanbot/titandash/bot/core/stats.py
  titanbot/titandash/bot/data/images/artifacts/artifacts.png
  titanbot/titandash/bot/data/images/artifacts/hades_orb.png
  titanbot/titandash/bot/data/images/artifacts/strange_fruit.png
  titanbot/titandash/models/statistics.py
Labels: bug, enhancement, important

#490 Titandash 2.0.3
  settings.py
  titanbot/titandash/bot/core/bot.py
  titanbot/titandash/bot/core/grabber.py
  titanbot/titandash/bot/core/maps.py
  titanbot/titandash/bot/core/stats.py
  titanbot/titandash/bot/data/images/artifacts/artifacts.png
  titanbot/titandash/bot/data/images/artifacts/hades_orb.png
  titanbot/titandash/bot/data/images/artifacts/strange_fruit.png
  titanbot/titandash/models/statistics.py
  version.json
Labels: major, version

#493 #492 Fix Issues With Goto Panel Functionality
  titanbot/titandash/bot/core/maps.py
  titanbot/titandash/bot/data/images/master/master.png
Labels: bug

#503 #484 Improve Minigame Behavior And Add Sleep To Taps
  titanbot/titandash/bot/core/bot.py
  titanbot/titandash/bot/core/maps.py
Labels: bug, enhancement

#505 #484 Improve Minigame Behavior And Add Sleep To Taps
  titanbot/titandash/bot/core/bot.py
  titanbot/titandash/bot/core/maps.py
Labels: bug, enhancement

#504 #500 Custom Tesseract Installation Not Found On Application Boot
  titanbot/titanbootstrap/admin.py
  titanbot/titanbootstrap/migrations/0001_initial.py
  titanbot/titanbootstrap/models/__init__.py
  titanbot/titanbootstrap/models/settings.py
  titanbot/titanbootstrap/views.py
Labels: bug, enhancement

#508 #507 Fixing Tapping Map for Astral Awakening to bypass 'Special Offer' Icon
  titanbot/titandash/bot/core/maps.py
Labels: bug

#511 #510 Remove Instances Of Nox Support In Docs/Code
  README.md
  titanbot/titandash/bot/core/constants.py
  titanbot/titandash/bot/core/window.py
Labels: enhancement

#513 #512 Fixup Window Implemetation To Support MEmu Only
  titanbot/titandash/bot/core/bot.py
  titanbot/titandash/bot/core/window.py
Labels: enhancement

#499 #495 Tap Routine Stuck In Collapsed/No Panel Checks
  titanbot/titandash/bot/core/bot.py
Labels: bug, enhancement

#514 #495 Tap Routine Stuck In Collapsed/No Panel Checks
  titanbot/titandash/bot/core/bot.py
  titanbot/titandash/bot/core/decorators.py
  titanbot/titandash/bot/core/grabber.py
  titanbot/titandash/bot/core/maps.py
  titanbot/titandash/bot/core/utilities.py
  titanbot/titandash/bot/data/images/no_panels/icon_boss.png
  titanbot/titandash/context_processors.py
  titanbot/titandash/migrations/0044_globalsettings_welcome_screen_checks_settings.py
  titanbot/titandash/migrations/0045_globalsettings_rate_screen_checks_settings.py
  titanbot/titandash/models/globals.py
  titanbot/titandash/templates/dashboard.html
  titanbot/titandash/templates/globals.html
  titanbot/titandash/templates/projectSettings.html
  titanbot/titandash/views.py
Labels: bug, enhancement

#524 #523 Fix Level Heroes Skipping Drag/Click Due To Static Headers
  titanbot/titandash/bot/core/bot.py
Labels: bug, important

#525 #521 Improve Fail Safe Mechanism Timings
  titanbot/titandash/bot/core/decorators.py
Labels: enhancement

#526 #519 Update Pi-Hole Global Setting Help Text
  titanbot/titandash/migrations/0046_auto_20200422_1933.py
  titanbot/titandash/models/globals.py
  titanbot/titandash/templates/globals.html
Labels: enhancement

#528 #527 Improve Headgear Swapping Efficiency
  titanbot/titandash/bot/core/bot.py
  titanbot/titandash/bot/core/maps.py
Labels: enhancement, performance

#530 #529 Fixup Minigames/Tapping Functions
  titanbot/titandash/bot/core/bot.py
Labels: enhancement

#531 #520 Add Summon Dagger To Supported Minigames
  titanbot/titandash/bot/core/bot.py
  titanbot/titandash/bot/core/maps.py
  titanbot/titandash/migrations/0047_add_summon_dagger_minigame_fixup_forbidden.py
  titanbot/titandash/models/configuration.py
  titanbot/titandash/templates/configurations/configuration_form.html
Labels: enhancement

#532 Titandash 2.0.5
  titanbot/titandash/bot/core/bot.py
  titanbot/titandash/bot/core/decorators.py
  titanbot/titandash/bot/core/maps.py
  titanbot/titandash/migrations/0046_auto_20200422_1933.py
  titanbot/titandash/migrations/0047_add_summon_dagger_minigame_fixup_forbidden.py
  titanbot/titandash/models/configuration.py
  titanbot/titandash/models/globals.py
  titanbot/titandash/templates/configurations/configuration_form.html
  titanbot/titandash/templates/globals.html
  version.json
Labels: bug, enhancement, important, performance, version

#536 #535 Fix Non-Pause In Goto Equipment Functionality.
  titanbot/titandash/bot/core/bot.py
Labels: bug

#538 #537 Bot Instances Only Log To Files On Their First Initialization
  titanbot/titandash/bot/core/utilities.py
Labels: bug, important

#540 #533 Add Tournament Result Parsing
  README.md
  settings.py
  titanbot/titanbot/settings.py
  titanbot/titandash/admin.py
  titanbot/titandash/bot/core/bot.py
  titanbot/titandash/bot/core/constants.py
  titanbot/titandash/bot/core/maps.py
  titanbot/titandash/bot/core/stats.py
  titanbot/titandash/bot/core/window.py
  titanbot/titandash/bot/data/images/tournament/in_top_ten.png
  titanbot/titandash/migrations/0048_tournament_parsing.py
  titanbot/titandash/migrations/0049_remove_clan_results.py
  titanbot/titandash/models/clan.py
  titanbot/titandash/models/configuration.py
  titanbot/titandash/models/tournament.py
  titanbot/titandash/static/js/configurations/configuration.js
  titanbot/titandash/static/js/tournaments/tournament.js
  titanbot/titandash/static/js/tournaments/tournaments.js
  titanbot/titandash/templates/base.html
  titanbot/titandash/templates/configurations/configuration_form.html
  titanbot/titandash/templates/dashboard.html
  titanbot/titandash/templates/raids/raid.html
  titanbot/titandash/templates/raids/raids.html
  titanbot/titandash/templates/raids/raidsTable.html
  titanbot/titandash/templates/tournaments/tournament.html
  titanbot/titandash/templates/tournaments/tournaments.html
  titanbot/titandash/templates/tournaments/tournamentsTable.html
  titanbot/titandash/urls.py
  titanbot/titandash/views.py
Labels: enhancement, idea, major

#541 #539 Improve Statistics Update OCR Checks And Accuracy
  titanbot/titandash/bot/core/bot.py
  titanbot/titandash/bot/core/maps.py
  titanbot/titandash/bot/core/stats.py
  titanbot/titandash/migrations/0050_gamestatistics_tournament_points.py
  titanbot/titandash/models/statistics.py
Labels: bug, enhancement

#542 Titandash 2.0.6
  README.md
  settings.py
  titanbot/titanbot/settings.py
  titanbot/titandash/admin.py
  titanbot/titandash/bot/core/bot.py
  titanbot/titandash/bot/core/constants.py
  titanbot/titandash/bot/core/grabber.py
  titanbot/titandash/bot/core/maps.py
  titanbot/titandash/bot/core/stats.py
  titanbot/titandash/bot/core/utilities.py
  titanbot/titandash/bot/core/window.py
  titanbot/titandash/bot/data/images/tournament/in_top_ten.png
  titanbot/titandash/migrations/0048_tournament_parsing.py
  titanbot/titandash/migrations/0049_remove_clan_results.py
  titanbot/titandash/migrations/0050_gamestatistics_tournament_points.py
  titanbot/titandash/models/clan.py
  titanbot/titandash/models/configuration.py
  titanbot/titandash/models/statistics.py
  titanbot/titandash/models/tournament.py
  titanbot/titandash/static/js/configurations/configuration.js
  titanbot/titandash/static/js/tournaments/tournament.js
  titanbot/titandash/static/js/tournaments/tournaments.js
  titanbot/titandash/templates/base.html
  titanbot/titandash/templates/configurations/configuration_form.html
  titanbot/titandash/templates/dashboard.html
  titanbot/titandash/templates/raids/raid.html
  titanbot/titandash/templates/raids/raids.html
  titanbot/titandash/templates/raids/raidsTable.html
  titanbot/titandash/templates/tournaments/tournament.html
  titanbot/titandash/templates/tournaments/tournaments.html
  titanbot/titandash/templates/tournaments/tournamentsTable.html
  titanbot/titandash/urls.py
  titanbot/titandash/views.py
  version.json
Labels: major, version
